<a href="https://colab.research.google.com/github/MsShwetaDubey/Pythonday1/blob/main/pythonbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [ ]:
math.sqrt(256)

16.0

In [ ]:
round(2.678,2)
math.sqrt(4)

2.0

In [ ]:
3<5

True

In [ ]:
4>9

False

In [ ]:
5+6

11

In [ ]:
8-9

-1

In [ ]:
7/8

0.875

In [ ]:
5555*666

3699630

In [ ]:
5>=6

False

In [ ]:
7<=3

False

In [ ]:
3==4

False

In [ ]:
(3>5)&(4<5)

False

In [ ]:
a='hello world'
b='hello dubbu'
c=a|b
print(c)

TypeError: ignored

In [ ]:
i=0
while i<=7:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7


In [ ]:
i=0
while i<=7:
  print(i)
  i=i+1
print("while loop ends")

0
1
2
3
4
5
6
7
while loop ends


In [ ]:
i=10
while i<=7:
  print(i)
  i=i+1
print("while loop ends")

0
1
2
3
4
5
6
7
while loop ends


In [ ]:
i=10
while i<=7:
  print(i)
  i=i+0
print("while loop ends")

while loop ends


In [ ]:
range(6)

range(0, 6)

In [ ]:

for i in range(6):
  print(+i)


0
1
2
3
4
5


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)
    


0.7819394583008651
greater than 1


In [ ]:
result= None
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)
    


0.5289111387283125
None


In [ ]:
result= None
x=randn()
if x>1:
  result="greater than 1"
else:
  result="less than 1"
print(x)
print(result)
    


-0.8136772374846366
less than 1


In [ ]:
result= None ##chained if statement
x=randn()
if x>1:
  result="greater than 1"
elif x<=-1:
  result="less than -1"
else:
  result="between -1 and 1"
print(x)
print(result)
    


0.6225527661583818
between -1 and 1


In [58]:
#creating a list

In [59]:
list1 = [1,2,3,'abc',"good job",True,30.7]

In [60]:
type(list1)

list

In [61]:
list1[0]

1

In [ ]:
#indexing in python strts from 0

In [ ]:
#last else,emt extracting is by list[-1]

In [63]:
list1[2]="dubbu"

In [64]:
list1


[1, 2, 'dubbu', 'abc', 'good job', True, 30.7]

In [ ]:
#getting data from list or slicing

In [65]:
list1[2:5]

['dubbu', 'abc', 'good job']

In [ ]:
#list[strting index:ending index+1]
#012345
#ulta is -1-2-3

In [ ]:
#advance slicing with ::

In [ ]:
#if every second element is required then its ::

In [66]:
list1[::2]

[1, 'dubbu', 'good job', 30.7]

In [67]:
list1[::-2]

[30.7, 'good job', 'dubbu', 1]

In [69]:
tuple1=(1.2,1,4,'shweta')

In [71]:
tuple1[2]='dubbu'


TypeError: ignored

In [72]:
len(list1)

7

In [73]:
max(list1)

TypeError: ignored

In [76]:
list2 =[1,3,4,5,7]
max(list2)

7

In [77]:
min(list2)

1

In [79]:
len(list2)

5

In [80]:
print(list2)

[1, 3, 4, 5, 7]


In [82]:
list2

[1, 3, 4, 5, 7]

In [ ]:
#arrays

import numpy as np
 

In [83]:
a=np.array(list1)
print(a)

['1' '2' 'dubbu' 'abc' 'good job' 'True' '30.7']


In [84]:
a

array(['1', '2', 'dubbu', 'abc', 'good job', 'True', '30.7'], dtype='<U32')

In [ ]:
#<U32 datatype U=unicode 32 bit

In [85]:
a=np.array(list2)
print(a)

[1 3 4 5 7]


In [86]:
a

array([1, 3, 4, 5, 7])

In [88]:
b=np.array([2345,3435,2365,-7689])

In [89]:
b.mean()

114.0

In [90]:
b

array([ 2345,  3435,  2365, -7689])

In [91]:
b[::2]

array([2345, 2365])

In [92]:
b[1::2]

array([ 3435, -7689])

In [95]:
b

array([ 2345,  3435,  2365, -7689])

In [97]:
c=b[2:4]

In [98]:
c

array([ 2365, -7689])

In [99]:
b

array([ 2345,  3435,  2365, -7689])

In [87]:
b.mean()

AttributeError: ignored

In [ ]:
(4==5)|(6>5)

True